### ISSUE TITLE
Object.values() gives an error - node.js version support?

### ISSUE THREAD

**Issue by pgalbavy** [HM-RedMatic/node-red-contrib-combine#2]
Sorry if I'm not an expert in node.js or node-red, but tried installing this on node-red on ubuntu 17.10 which runs node.js 6.11.x - I then got errors from the statistics node that Object.values() in combine() "TypeError: Object.values is not a function"

I think, from reading online, this is because it requires node.js 7.x support, which I don't have.

If this is the case then can I suggest a note or dependency to avoid others making the same mistake on install?

**Comment by hobbyquaker** [comment]
Thx for pointing that out, will fix the `engine` entry in package.json asap, than it will at least throw a warning on installation, also I will add a hint to the Readme.
