### ISSUE TITLE
List Node Delay

### ISSUE THREAD

**Issue by krzydec** [HM-RedMatic/node-red-contrib-combine#7]
Hello

I have got a problem with using List Node from your package.
The problem starts when I enable Timeout function 

![image](https://user-images.githubusercontent.com/9840399/49877047-7927f000-fe1c-11e8-9fda-7338ad3572c5.png)
It is causing the following error:

![image](https://user-images.githubusercontent.com/9840399/49876782-fbfc7b00-fe1b-11e8-953c-558c93f1a391.png)

Please help, as the Node output data in the format I want, just need to dump the stored information every 1 s.

**Comment by Sineos** [comment]
In combine-list.js please add

```
        remove(key) {
            delete this.msgs[key];
            const msg = this.combine();

            this.send(msg);
        }
```

after line 39 and try again (restart NR)

**Comment by krzydec** [comment]
Hello.

Thank you for your help. It is working now.
The Node Red Server is not crashing after your modifications.
